### ISSUE TITLE
Tests are not running

### ISSUE THREAD

**Issue by jules2689** [notwaldorf/flash-cards#14]
I wasn't able to get tests running. I've included an attempted run and debug log below.
This is on a clean master after `npm install` has run. The app runs without issue.

The issue seems to be in a node module.

<details>
<summary>Attempted Run</summary>
<pre>
~/src/github.com/jules2689/flash-cards(master*) ➜ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
~/src/github.com/jules2689/flash-cards(master*) ➜ npm run test

> flash-cards@0.8.0 test /Users/juliannadeau/src/github.com/jules2689/flash-cards
> npm run test:unit && npm run test:integration

> flash-cards@0.8.0 test:unit /Users/juliannadeau/src/github.com/jules2689/flash-cards
> polymer test --module-resolution=node --npm -l chrome -l firefox

TypeError: Cannot read property '1' of null

error: [cli.main]   cli runtime exception: TypeError: Cannot read property '1' of null
error: [cli.main]   TypeError: Cannot read property '1' of null
    at module.exports (/Users/juliannadeau/src/github.com/jules2689/flash-cards/node_modules/polymer-cli/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/Users/juliannadeau/src/github.com/jules2689/flash-cards/node_modules/polymer-cli/node_modules/promisify-node/index.js:61:29)
    at processExports (/Users/juliannadeau/src/github.com/jules2689/flash-cards/node_modules/polymer-cli/node_modules/promisify-node/index.js:82:25)
    at processExports (/Users/juliannadeau/src/github.com/jules2689/flash-cards/node_modules/polymer-cli/node_modules/promisify-node/index.js:82:25)
    at processExports (/Users/juliannadeau/src/github.com/jules2689/flash-cards/node_modules/polymer-cli/node_modules/promisify-node/index.js:82:25)
    at module.exports (/Users/juliannadeau/src/github.com/jules2689/flash-cards/node_modules/polymer-cli/node_modules/promisify-node/index.js:164:10)
    at /Users/juliannadeau/src/github.com/jules2689/flash-cards/node_modules/polymer-cli/node_modules/web-component-tester/runner/paths.js:49:23
    at Generator.next (<anonymous>)
    at /Users/juliannadeau/src/github.com/jules2689/flash-cards/node_modules/polymer-cli/node_modules/web-component-tester/runner/paths.js:20:71
    at new Promise (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flash-cards@0.8.0 test:unit: `polymer test --module-resolution=node --npm -l chrome -l firefox`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flash-cards@0.8.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juliannadeau/.npm/_logs/2018-05-12T16_10_37_125Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flash-cards@0.8.0 test: `npm run test:unit && npm run test:integration`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the flash-cards@0.8.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juliannadeau/.npm/_logs/2018-05-12T16_10_37_148Z-debug.log
</pre>
</details>

<details>
<summary>Debug Log</summary>
<pre>
~/src/github.com/jules2689/flash-cards(master*) ➜ cat /Users/juliannadeau/.npm/_logs/2018-05-12T16_10_37_148Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.0.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'test' ]
2 info using npm@5.6.0
3 info using node@v10.0.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle flash-cards@0.8.0~pretest: flash-cards@0.8.0
6 info lifecycle flash-cards@0.8.0~test: flash-cards@0.8.0
7 verbose lifecycle flash-cards@0.8.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle flash-cards@0.8.0~test: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/juliannadeau/src/github.com/jules2689/flash-cards/node_modules/.bin:~/src/github.com/Shopify/dex/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/git/bin:/user/local:/Applications/VMware Fusion.app/contents/Library:/Applications/Postgres.app/Contents/MacOS/bin:/Users/juliannadeau/.gem/ruby/2.4.3/bin/rubocop:/Users/juliannadeau/.gem/ruby/2.4.3/bin:/opt/rubies/2.4.3/lib/ruby/gems/2.4.0/bin:/opt/rubies/2.4.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/Users/juliannadeau/Library/Android/sdk/platform-tools:/Users/juliannadeau/Library/Android/sdk/tools/bin:/Users/juliannadeau/src/github.com/jules2689/task/bin:/Users/juliannadeau/bin
9 verbose lifecycle flash-cards@0.8.0~test: CWD: /Users/juliannadeau/src/github.com/jules2689/flash-cards
10 silly lifecycle flash-cards@0.8.0~test: Args: [ '-c', 'npm run test:unit && npm run test:integration' ]
11 silly lifecycle flash-cards@0.8.0~test: Returned: code: 1  signal: null
12 info lifecycle flash-cards@0.8.0~test: Failed to exec test script
13 verbose stack Error: flash-cards@0.8.0 test: `npm run test:unit && npm run test:integration`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:947:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
14 verbose pkgid flash-cards@0.8.0
15 verbose cwd /Users/juliannadeau/src/github.com/jules2689/flash-cards
16 verbose Darwin 17.5.0
17 verbose argv "/usr/local/Cellar/node/10.0.0/bin/node" "/usr/local/bin/npm" "run" "test"
18 verbose node v10.0.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error flash-cards@0.8.0 test: `npm run test:unit && npm run test:integration`
22 error Exit status 1
23 error Failed at the flash-cards@0.8.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
</pre>
</details>

**Comment by notwaldorf** [comment]
Yup, it’s already listed as a known issue in the readme

**Comment by jules2689** [comment]
Oh darn. I didn't read to the bottom.
Sorry!
